[env]
TPCH_SAMPLING_RATE = "0.1"
TPCH_DATA_PATH = "test_files/tpch/data"

[tasks.generate_tpch_data]
description = "Clone TPCH data if it doesn't already exist"
script = [
    '''
    ./scripts/generate-tpch-data.sh
    '''
]

[tasks.run_tests]
description = "Run tests"
command = "cargo"
args = ["test"]

[tasks.test]
description = "Clone TPCH data and run tests"
dependencies = ["generate_tpch_data", "run_tests"]
