apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: datafusion-ray-pipeline
build:
  artifacts:
    - image: apache/datafusion-ray
      docker:
        dockerfile: k8s/Dockerfile
        buildArgs:
          CARGO_HOME: /usr/local/cargo
        cacheFrom:
          - ghcr.io/apache/datafusion-ray:latest
      context: ../..
  local:
    useBuildkit: true
deploy:
  helm:
    releases:
      - name: kuberay-operator
        repo: "https://ray-project.github.io/kuberay-helm/"
        remoteChart: kuberay-operator
        namespace: default
        version: "1.1.0"
      - name: raycluster
        repo: "https://ray-project.github.io/kuberay-helm/"
        remoteChart: ray-cluster
        namespace: default
        version: "1.1.0"
        setValues:
          image.repository: "apache/datafusion-ray"
          imagePullPolicy: Always
        setValueTemplates:
          image.tag: "{{.IMAGE_TAG}}"
  kubectl: {}
