name: Rust

on:
  push:

env:
  CARGO_TERM_COLOR: always
  TPCH_SAMPLING_RATE: 0.1
  TPCH_DATA_PATH: test_files/tpch/data

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install protobuf compiler
        shell: bash
        run: sudo apt-get install protobuf-compiler
      - name: Build Rust code
        run: cargo build --verbose
      - name: Generate TPCH
        run: |
          cargo install cargo-make
          cargo make test --verbose
